// <auto-generated />
using System;
using DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(RailwayContext))]
    [Migration("20250315124652_AddDateToTicketFixed")]
    partial class AddDateToTicketFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Station", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Stations_pkey1");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("DAL.Entities.StationsTrain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"Stations_Id_seq\"'::regclass)");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<long?>("StationId")
                        .HasColumnType("bigint");

                    b.Property<long>("TrainNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("Stations_pkey");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainNumber");

                    b.ToTable("Stations-Trains", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SeatNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("StationTrainId1")
                        .HasColumnType("bigint");

                    b.Property<long>("StationTrainId2")
                        .HasColumnType("bigint");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("WagonNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("Tickets_pkey");

                    b.HasIndex("StationTrainId1");

                    b.HasIndex("StationTrainId2");

                    b.HasIndex("UserEmail");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DAL.Entities.Train", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberOfSeats")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberOfWagons")
                        .HasColumnType("bigint");

                    b.Property<long>("PricePerInterval")
                        .HasColumnType("bigint");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Trains_pkey");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Email")
                        .HasName("Users_pkey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL.Entities.StationsTrain", b =>
                {
                    b.HasOne("DAL.Entities.Station", "Station")
                        .WithMany("StationsTrains")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("StationFK");

                    b.HasOne("DAL.Entities.Train", "TrainNumberNavigation")
                        .WithMany("StationsTrains")
                        .HasForeignKey("TrainNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TrainFK");

                    b.Navigation("Station");

                    b.Navigation("TrainNumberNavigation");
                });

            modelBuilder.Entity("DAL.Entities.Ticket", b =>
                {
                    b.HasOne("DAL.Entities.StationsTrain", "StationTrainId1Navigation")
                        .WithMany("TicketStationTrainId1Navigations")
                        .HasForeignKey("StationTrainId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("StationTrainFK1");

                    b.HasOne("DAL.Entities.StationsTrain", "StationTrainId2Navigation")
                        .WithMany("TicketSationTrainId2Navigations")
                        .HasForeignKey("StationTrainId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("StationTrainFK2");

                    b.HasOne("DAL.Entities.User", "UserEmailNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserFK");

                    b.Navigation("StationTrainId1Navigation");

                    b.Navigation("StationTrainId2Navigation");

                    b.Navigation("UserEmailNavigation");
                });

            modelBuilder.Entity("DAL.Entities.Station", b =>
                {
                    b.Navigation("StationsTrains");
                });

            modelBuilder.Entity("DAL.Entities.StationsTrain", b =>
                {
                    b.Navigation("TicketSationTrainId2Navigations");

                    b.Navigation("TicketStationTrainId1Navigations");
                });

            modelBuilder.Entity("DAL.Entities.Train", b =>
                {
                    b.Navigation("StationsTrains");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
